## **Задача 1**. Посчитайте количество обучаемых параметров в сети net_seq и net_model.

(3 + 1) * 5 + (5 + 1) * 2 = 32

## **Задача 2**. Cделать нейрон, соответствующий оператору НЕ.

In [ ]:
import torch

In [3]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(1, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))

In [4]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[-0.1091]], requires_grad=True),
 Parameter containing:
 tensor([0.7349], requires_grad=True))

In [5]:
neuron.fc.weight.data = torch.tensor([[-1.0]])
neuron.fc.bias.data = torch.tensor([0.1])
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[-1.]], requires_grad=True),
 Parameter containing:
 tensor([0.1000], requires_grad=True))

In [6]:
x = torch.tensor([1.0])
neuron(x)

tensor([0.], grad_fn=<NotImplemented>)

## **Задача 3**. Cделать нейрон, соответствующий оператору И.

In [28]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))

In [29]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[ 0.5424, -0.4504]], requires_grad=True),
 Parameter containing:
 tensor([0.0197], requires_grad=True))

In [30]:
neuron.fc.weight.data = torch.tensor([[1., 1.]])
neuron.fc.bias.data = torch.tensor([-1.5])

In [31]:
x = torch.tensor([[0.0, 0.0],
                  [0.0, 1.0],
                  [1.0, 0.0],
                  [1.0, 1.0],])
print(neuron(x))
assert neuron(x).flatten().tolist() == [0,0,0,1]

tensor([[0.],
        [0.],
        [0.],
        [1.]], grad_fn=<NotImplemented>)


## **Задача 4**. Cделать нейрон, соответствующий оператору ИЛИ.

In [11]:
neuron.fc.weight.data = torch.tensor([[0.5, 0.5]])
neuron.fc.bias.data = torch.tensor([0.0])

In [36]:
x = torch.tensor([[0.0, 0.0],
                  [0.0, 1.0],
                  [1.0, 0.0],
                  [1.0, 1.0],])
assert neuron(x).flatten().tolist() == [0,1,1,1]

## **Задача 5**. Cделать нейрон, соответствующий оператору XOR.

In [13]:
neuron.fc.weight.data = torch.tensor([[0.0, 0.0]])
neuron.fc.bias.data = torch.tensor([0.0])

In [14]:
x = torch.tensor([0.0, 0.0])
neuron(x)

tensor([0.], grad_fn=<NotImplemented>)

## **Вопрос 1**. Какие нейронные сети могут иметь только линейную разделяющую поверхность?

Имеющие линейную функцию активации

## **Вопрос 2**. Имеет ли смысл соединять полносвязанные нейроны (нейроны, которые принимают на вход все выходы предыдущего слоя) с линейной функцией активации в многослойную нейронную сеть?

Нет, так как коэффициенты будут просто накапливаться в линейной размерности

# **Домашнее задание**

Дедлайн домашнего задания - текущее воскресенье 23:59. 

# **Домашнее задание 0:** 
Создайте репозиторий на Github. Вся дальнейшая домашка загружается туда. Чуть позже в телеграм чате будет выложена форма для сдачи.

# **Домашнее задание 1:** 
Реализуйте XOR с помощью 3 нейронов. Запишите ответ в виде выражения, состоящего из объектов neuron() – моделей нейрона с пороговой функцией активации, внутри скобок может быть что угодно. Входы верхнего уровня называются x1 и x2. Пример фрагмента записи: neuron(1*x1 + 5*x2 - 0.1) + neuron(x1) (ответ будет выглядеть чуть сложнее, но других символов вроде && не потребуется).

xor = neuron(neuron(-x1 - x2 + 1.5) + neuron (0.5x1 + 0.5x2) - 1.5)

#### Проверка:

In [41]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))

neuron = Neuron()
x = torch.tensor([[0.0, 0.0],
                  [0.0, 1.0],
                  [1.0, 0.0],
                  [1.0, 1.0],])

neuron.fc.weight.data = torch.Tensor([[-1, -1]])
neuron.fc.bias.data = torch.Tensor([[1.5]])
n1 = neuron(x)

neuron.fc.weight.data = torch.Tensor([[0.5, 0.5]])
neuron.fc.bias.data = torch.Tensor([[0]])
n2 = neuron(x)

neuron.fc.weight.data = torch.Tensor([[1, 1]])
neuron.fc.bias.data = torch.Tensor([[-1.5]])
n3 = neuron(torch.cat((n1, n2), 1))

assert n3.flatten().tolist() == [0,1,1,0]

# **Домашнее задание 2:** 
Нарисуйте backward граф для выражения `a*b+c*d`. [Теория и пример оформления](https://www.youtube.com/watch?v=MswxJw-8PvE). Сравните полученные теоретические значения с аттрибутами grad у исходных тензоров.

![Image alt](%D0%B3%D1%80%D0%B0%D1%84%20%D0%B1%D1%8D%D0%BA.png)

In [12]:
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([4.0], requires_grad=True)
c = torch.tensor([1.0], requires_grad=True)
d = torch.tensor([5.0], requires_grad=False)

In [13]:
print(a.grad)

None


In [14]:
loss = a*b + c*d
loss.backward()

In [18]:
print(b.grad)

tensor([2.])


# **Домашнее задание 3:** 
Поэксперементируйте с размером тензоров, которые влезут на видеоркарту в Colab. Найдите максимальный размер тензора для типа данных float32, float64, float16, int32, int64. На сколько они отличаются.

In [1]:
import torch

In [9]:
!nvidia-smi

Wed Nov 30 16:44:11 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0    27W /  70W |    610MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [104]:
import gc

del a
gc.collect()
with torch.no_grad():
    torch.cuda.empty_cache()

In [38]:
torch.cuda.memory_reserved()

15091105792

In [52]:
torch.cuda.memory_allocated()

0

Максимум для float32

In [80]:
a=torch.zeros(4096, 927872, dtype=torch.float32,device='cuda')

In [81]:
!nvidia-smi

Wed Nov 30 16:55:45 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    28W /  70W |  15106MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Максимум для float64

In [95]:
a=torch.zeros(4096, 927872//2, dtype=torch.float64,device='cuda')

In [96]:
!nvidia-smi

Wed Nov 30 16:58:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P0    28W /  70W |  15106MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Максимум для float16

In [99]:
a=torch.zeros(4096, 927872*2, dtype=torch.float16,device='cuda')

In [100]:
!nvidia-smi

Wed Nov 30 16:59:45 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P0    28W /  70W |  15106MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Максимум для int32

In [102]:
a=torch.zeros(4096, 927872, dtype=torch.int32,device='cuda')

In [103]:
!nvidia-smi

Wed Nov 30 17:01:32 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P0    28W /  70W |  15106MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [105]:
a=torch.zeros(4096, 927872//2, dtype=torch.int64,device='cuda')

In [106]:
!nvidia-smi

Wed Nov 30 17:01:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P0    28W /  70W |  15106MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Все типы данных занимают по 2, 4, 8 байт, поэтому их размер отличается соответственно в 2, 4, 8 раз

 # **Домашнее задание 4:** 
 Напишите хороший пример неэффективного кода для занятия памяти видеокарты, который вызовет ошибку out of memory

In [11]:
import gc

#del a
gc.collect()
with torch.no_grad():
    torch.cuda.empty_cache()

In [12]:
!nvidia-smi

Thu Dec  1 14:47:14 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 526.98       Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   57C    P8     5W /  N/A |    428MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [13]:
import torch

def allocate_empty_tensor(dim_size):
  a=torch.zeros(4096,dim_size,dtype=torch.float32,device='cuda')

i = 1024
while True:
    a = allocate_empty_tensor(i)
    print(torch.cuda.memory_reserved())
    i += 1024

16777216
50331648
100663296
167772160
251658240
352321536
469762048
603979776
754974720
922746880
1107296256
1308622848
1526726656
1761607680
2013265920
2281701376
2566914048
2868903936
3187671040
3523215360
352321536
721420288
1107296256
1509949440
1929379840
2365587456
2818572288
3288334336
486539264
989855744
1509949440
2046820352
2600468480
3170893824
587202560
1191182336
1811939328
2449473536
3103784960
671088640
1358954496
2063597568
2785017856
3523215360
754974720
1526726656
2315255808
3120562176
822083584
1660944384
2516582400
3388997632
889192448
1795162112
2717908992
3657433088
956301312
1929379840
2919235584
1006632960
2030043136
3070230528
1056964608
2130706432
3221225472
1107296256
2231369728
3372220416
1157627904
2332033024
3523215360
1207959552
2432696320
3674210304
1258291200
2533359616
1291845632
2600468480
1325400064
2667577344
1358954496
2734686208
1392508928
2801795072
1426063360
2868903936
1459617792
2936012800
1493172224
3003121664
1526726656
3070230528
1560281088

RuntimeError: CUDA out of memory. Tried to allocate 3.47 GiB (GPU 0; 4.00 GiB total capacity; 0 bytes already allocated; 2.86 GiB free; 0 bytes reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

# **Домашнее задание 5:** 
Используя один линейный слой `nn.Linear` и один входной тензор `x` подберите подберите размерности так, чтобы занимать всю видеопамять.
Попробуйте применить линейный слой к тензору `x`. Что произойдет? Кратко опишите ваши эксперименты. Что вы поняли?

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [7]:
!nvidia-smi

Thu Dec  1 12:46:26 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    26W /  70W |  15074MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
layer = torch.nn.Linear(4096*4096, 225, device = 'cuda')


In [6]:
a=torch.zeros(4096*4096, dtype=torch.float32, device='cuda')

In [8]:
res = layer(a)

RuntimeError: ignored

Если создавать слой или тензор без параметра `device = 'cuda'`, то он создается сначала в оперативной памяти, а уже после, применяя .cuda() мы переносим его на видеокарту. Поэтому невозможно занять больше памяти, чем есть ОЗУ без параметра device

# Рекомендуемые ссылки

- [Нейронные сети и компьютерное зрение, Samsung AI Center, часть 1](https://stepik.org/course/50352/syllabus)
- [Cимулятор](https://playground.tensorflow.org/) нейронов и нейронных сетей